version: "3"
services:
  app:
    build: .
    volumes:
      - ../ts_tutorial:/app
    ports:
      - "8080:8080"
    tty: true
    command: /bin/sh
    # command: npm start
    # typescript環境を作れたら、サーバを動かすコマンドを設定すると、docker-compose upするだけで、サーバが起動するようになる
